Investor Registry version 0.0.1
CertiKProject/certik-investor-registry pull request #1
Opened 2020-09-09 06:44 UTC by imh0wie

* Description will be added today.*

2020-09-09 18:36 UTC, bencao requested changes

2020-09-09 18:36 UTC, bencao commented on functions/src/investors.js
> +        validateCode(code);
validation won't work? since even it returns a bad the code will continue execution

2020-09-09 18:36 UTC, bencao commented on functions/src/lib/env.js
> +  return ensureAndGet("NODE_ENV");
NODE_ENV may be empty if not set by the environment

```
# node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> process.env.NODE_ENV
undefined
```

2020-09-09 18:36 UTC, bencao commented on package.json
> +    "prettier": "2.1.1"
netlify package should also in dev dependency?

2020-09-09 18:38 UTC, bencao commented
also deploy preview failed due to some lint warnings.

2020-09-09 19:37 UTC, imh0wie commented on functions/src/lib/env.js
> +  return ensureAndGet("NODE_ENV");
They should be there if added correctly at https://app.netlify.com/sites/certik-investory-registry/settings/deploys#environment

2020-09-12 06:52 UTC, bencao commented
@imh0wie will merge now, but remember to fix the validation issues.

2020-09-12 06:52 UTC, merged